name: test-docs-builder-setup

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  test:
    name: version=${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [edge, latest, '0.100.0', null]
    steps:
      - uses: actions/checkout@v6
      - uses: ./docs-builder/setup
        with:
          version: ${{ matrix.version }}
      - run: docs-builder --version
